In [2]:
import pandas as pd

In [3]:
populationdf = pd.read_csv('population.csv')

In [4]:
populationdf.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Dependency Ratio,Unnamed: 12,Unnamed: 13,Median Age,Unnamed: 15,Unnamed: 16
0,Name,Region,GENC,Year,Total Population,Growth Rate,Population Density (per sq km),Total Fertility Rate,Life Expectancy at Birth,Under-5 Mortality Rate,Sex Ratio of the Population,Youth and Old Age (0-14 and 65+),Youth (0-14),Old Age (65+),Both Sexes,Male,Female
1,-> 1950,NaN,NaN,NaN,--,--,--,--,--,--,--,--,--,--,--,--,--
2,Afghanistan,"1950,Afghanistan",AF,1950,"8,150,368",--,12.5,--,--,--,--,--,--,--,--,--,--
3,Albania,"1950,Albania",AL,1950,"1,227,156",--,44.8,--,--,--,--,--,--,--,--,--,--
4,Algeria,"1950,Algeria",DZ,1950,"8,892,718",--,3.7,--,--,--,--,--,--,--,--,--,--

In [8]:
#keep the columns that are not needed
population = populationdf['Name', 'Total Population', 'Year']

KeyError: ('Name', 'Total Population', 'Year')